[OpenNewsArchive]
# OpenXLab Access Key
access_key = <Access Key>
# OpenXLab Secret Key
secret_key = <Secret Key>
# 本地数据集下载目录
target_path = download_dir/OpenNewsArchive
# 可选：额外下载的单文件路径
source_path = /README.md
# 数据集 repo
dataset_repo = OpenDataLab/OpenNewsArchive
