[CommonCrawlNews]
# 要处理的年份
year = 2022,2023,2024,2025
# 要处理的月份，多个月份使用逗号分隔，例如：1,2,3,...,12
months = 1,2,3,4,5,6,7,8,9,10,11,12
# WARC 文件存放的根目录。程序会在此目录下按照年份和月份的结构查找 WARC 文件  注意修改为实际的 WARC 文件目录
WARC_FOLDER = ../../../../download_dir/CommonCrawl

# 结果输出目录，用于保存处理后的文本和 HTML 内容 注意修改为实际的输出目录
OUTPUT_DIR = outputs/CommonCrawlNews/keyword_filter

# 日志文件路径模板，用于记录处理过程中的日志信息
# 支持占位符：{year} 年份, {month} 月份（会自动替换为实际值）
# 日志文件将保存在 logs/keyword_filter/ 目录下
LOG_FILE_TEMPLATE = logs/keyword_filter/CommonCrawlNews_{year}_{month}.log
# 关键词文件路径，关键词以换行分隔，每行一个
KEYWORDS_FILE = keywords/Identification-common-keywords.txt

# 最大进程数，决定并发处理任务的数量
max_workers = 32

NLTK_DATA = punkt, stopwords, wordnet,punkt_tab

PHRASES_FILE = keywords/Identification-common-custom_phrases.txt

# 内容过滤
max_html_bytes = 25000000
allowed_content_types = text/html,application/xhtml+xml
fallback_soup_text = true

# URL 规范化
strip_utm_params = true

# 终端展示
use_progress_bar = true
console_stream_log = false

phrase_freq_bonus = 25
