[CN_News-llm_filter]
# 要处理的年份
year = 2022,2023,2024,2025
# 要处理的月份，多个月份使用逗号分隔，例如：1,2,3,...,12
months = 1,2,3,4,5,6,7,8,9,10,11,12
# AI相关新闻所在的目录。程序会在此目录下按照年份和月份的结构查找 AI相关 文件  注意修改为实际的 AI相关新闻 文件目录
BASE_INPUT_DIR = download_dir/cn_risk_news

# 结果输出目录，用于保存处理后的AI风险相关新闻 注意修改为实际的输出目录
BASE_OUTPUT_DIR = output/Identification_Method-CN_News-llm_filter
# 日志文件路径，用于记录处理过程中的日志信息
LOG_FILE = logs/Identification_Method-CN_News-llm_filter.log

# 关键词文件路径，关键词以换行分隔，每行一个
CONTENT_LIMIT = 10000

MAX_THREADS = 5 
# 默认线程数为5 防止AI风险检测API过载
BATCH_SIZE = 5
# 每批处理5个文件（与提示词一致）
