[Evaluation]

KEYWORDS_FILE = keywords/Identification-common-keywords.txt

PHRASES_FILE = keywords/Identification-common-custom_phrases.txt

STOPWORDS_FILE = keywords/Identification-common-stopwords.txt
LOG_FILE = logs/Identification_Evaluation_test.log

# AI相关新闻相关的输出文件 使用AIID_AIAAIC数据集进行评估 将其分为AI相关和非AI相关两类
AI_RELATED_OUTPUT = data/ai_related_news_AIID_AIAAIC.json
AI_UNRELATED_OUTPUT =  data/ai_unrelated_news_AIID_AIAAIC.json

BASE_INPUT_FILE = data/AIID_AIAAIC.json


phrase_freq_bonus = 25

PROMPT_FILE = prompt/Identification_Evaluation-prompt.txt
CLASSIFICATION_FILE = data/standard_incidents_classification.json
OUTPUT_PREDICTIONS_FILE = data/standard_cases_prompt_predictions.json
OUTPUT_SUMMARY_FILE = data/standard_cases_prompt_metrics.json
LLM_BATCH_SIZE = 5
OUTPUT_DETAIL_ROOT = data/standard_cases_detail
CONTENT_LIMIT = -1
LLM_CONCURRENCY = 5
